name: cidade_ativa
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  
  carousel_pro: ^0.0.13
  cupertino_icons: ^0.1.2  
  flutter_staggered_grid_view: "^0.2.2"  
  firebase_analytics: ^1.0.5
  firebase_messaging: ^2.0.3
  transparent_image: ^0.1.0
  scoped_model: ^0.3.0
  path_provider: ^0.4.1
  firebase_auth: ^0.6.2+1
  url_launcher: ^3.0.3  
  font_awesome_flutter: ^8.1.0
  cloud_firestore: ^0.8.2+3
  flutter_launcher_icons: ^0.6.1
  google_sign_in: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:   
  android: true 
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true  
  assets:
   - assets/images/backgroud.png
   - assets/images/logo.png
   - assets/images/icon_google.png
   - assets/1.png
   - assets/2.png
   - assets/3.png   
  
   - assets/images/full-bloom.png
   - assets/images/mountains.jpeg
   - assets/images/mountains.jpg

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

    - family: Aveny
      fonts:
        - asset: assets/fonts/AvenyTRegular.otf
          style: normal
        - asset: assets/fonts/AvenyTMedium.otf
          style: italic

    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf